# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Matvey\Desktop\Feniks7\add_obj_choice.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(543, 282)
        Form.setMaximumSize(Form.size())
        Form.setMinimumSize(Form.size())
        self.pushButton_taxpayer = QtWidgets.QPushButton(Form)
        self.pushButton_taxpayer.setGeometry(QtCore.QRect(120, 90, 77, 73))
        self.pushButton_taxpayer.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Matvey\\Desktop\\Feniks7\\icons/firm2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_taxpayer.setIcon(icon)
        self.pushButton_taxpayer.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_taxpayer.setObjectName("pushButton_taxpayer")
        self.pushButton_exebody = QtWidgets.QPushButton(Form)
        self.pushButton_exebody.setGeometry(QtCore.QRect(332, 90, 77, 73))
        self.pushButton_exebody.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Matvey\\Desktop\\Feniks7\\icons/workHuman.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exebody.setIcon(icon1)
        self.pushButton_exebody.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_exebody.setObjectName("pushButton_exebody")
        self.label_taxpayer = QtWidgets.QLabel(Form)
        self.label_taxpayer.setGeometry(QtCore.QRect(90, 180, 140, 18))
        self.label_taxpayer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_taxpayer.setObjectName("label_taxpayer")
        self.label_exebody = QtWidgets.QLabel(Form)
        self.label_exebody.setGeometry(QtCore.QRect(287, 180, 170, 18))
        self.label_exebody.setAlignment(QtCore.Qt.AlignCenter)
        self.label_exebody.setObjectName("label_exebody")

        # Добавить icon win
        icon_main = QtGui.QIcon()
        icon_main.addPixmap(QtGui.QPixmap("C:\\Users\\Matvey\\Desktop\\Feniks7\\icons/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon_main)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить..."))
        self.label_taxpayer.setText(_translate("Form", "Налогоплательщик"))
        self.label_exebody.setText(_translate("Form", "Исполнительный орган"))


