# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Matvey\Desktop\Feniks7\add_exebody.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMenu, QAction
from PyQt5.QtGui import QCursor


class Ui_Form(object):
    cell_selected = None
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(583, 330)
        self.comboBox_taxpayer = QtWidgets.QComboBox(Form)
        self.comboBox_taxpayer.setGeometry(QtCore.QRect(300, 10, 229, 22))
        self.comboBox_taxpayer.setObjectName("comboBox_taxpayer")
        self.pushButton_add_taxpayer = QtWidgets.QPushButton(Form)
        self.pushButton_add_taxpayer.setGeometry(QtCore.QRect(532, 9, 24, 24))
        self.pushButton_add_taxpayer.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Matvey\\Desktop\\Feniks7\\icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setMaximumSize(Form.size())
        Form.setMinimumSize(Form.size())
        self.pushButton_add_taxpayer.setIcon(icon)
        self.pushButton_add_taxpayer.setObjectName("pushButton_add_taxpayer")
        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setGeometry(QtCore.QRect(199, 270, 93, 28))
        self.pushButton_add.setObjectName("pushButton_add")

        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setGeometry(QtCore.QRect(300, 270, 93, 28))
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 516, 214))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_last_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_last_name.setObjectName("label_last_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_last_name)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_first_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_first_name.setObjectName("label_first_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_first_name)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_middle_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_middle_name.setObjectName("label_middle_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_middle_name)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_birthday = QtWidgets.QLabel(self.layoutWidget)
        self.label_birthday.setObjectName("label_birthday")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_birthday)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setCalendarPopup(True)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_addres = QtWidgets.QLabel(self.layoutWidget)
        self.label_addres.setObjectName("label_addres")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_addres)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_email = QtWidgets.QLabel(self.layoutWidget)
        self.label_email.setObjectName("label_email")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_email)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_phone_num = QtWidgets.QLabel(self.layoutWidget)
        self.label_phone_num.setObjectName("label_phone_num")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_phone_num)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.horizontalLayout.addLayout(self.formLayout)
        self.tableView_taxpayer = QtWidgets.QTableView(self.layoutWidget)
        self.tableView_taxpayer.setObjectName("tableView_taxpayer")
        self.tableView_taxpayer.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.delete_link_action = QAction('Удалить')
        self.horizontalLayout.addWidget(self.tableView_taxpayer)

        # Добавить icon win
        icon_main = QtGui.QIcon()
        icon_main.addPixmap(QtGui.QPixmap("C:\\Users\\Matvey\\Desktop\\Feniks7\\icons/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon_main)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить исполнительного органа"))
        self.pushButton_add.setText(_translate("Form", "Добавить"))
        self.pushButton_cancel.setText(_translate("Form", "Отмена"))
        self.label_last_name.setText(_translate("Form", "Фамилия:"))
        self.label_first_name.setText(_translate("Form", "Имя:"))
        self.label_middle_name.setText(_translate("Form", "Отчество:"))
        self.label_birthday.setText(_translate("Form", "Дата рождения:"))
        self.label_addres.setText(_translate("Form", "Домашний адрес:"))
        self.label_email.setText(_translate("Form", "E-mail:"))
        self.label_phone_num.setText(_translate("Form", "Номер телефона:"))

    def call_contextMenu(self, pos):
        menu = QMenu(self.tableView_taxpayer)
        deleteAction = menu.addAction(self.delete_link_action)
        menu.exec_(QCursor().pos())

    def delete_link(self, model, id_exebody, db, cursor, Form):
        id_taxpayer = model.record(self.cell_selected.row()).value(0)

        sql_request = 'DELETE FROM link_payer_exebody WHERE executive_body=' + str(id_exebody) + ' AND ' + 'taxpayer=' + str(id_taxpayer)
        cursor.execute(sql_request)
        db.commit()

        Form.close()
        del Form

        model.setQuery(model.query().lastQuery())

    def get_cell_selected (self, cell):
        self.cell_selected = cell



